# backend/card_catalog.py
# Effective cashback % per category for popular Indian credit cards.
# For reward-point cards, rates are expressed as cash-equivalent %.
# e.g. 10 RP per ₹100 at 1 RP = ₹0.25  →  2.5% effective cashback

CARD_CATALOG = {
    "hdfc_millennia": {
        "display_name": "HDFC Millennia",
        "issuer": "HDFC",
        "annual_fee": 1000,
        "fee_waiver_spend": 100000,
        "cashback": {
            "Online Shopping": 5.0,
            "Grocery":         5.0,
            "Food & Dining":   2.5,
            "Transport":       2.5,
            "Entertainment":   2.5,
            "Travel":          2.5,
            "Utilities & Bills": 1.0,
            "Fuel":            1.0,
            "Health":          1.0,
            "Other":           1.0,
            "Cash Advance":    0.0,
        },
        "offline_cashback": {
            "_default": 1.0,
            "Cash Advance": 0.0,
        },
        "monthly_cashback_cap": 1000,
        "notes": "5% on Amazon, Flipkart, Myntra, Bigbasket; 2.5% on Swiggy, Zomato, Uber, Ola, MakeMyTrip; 1% on all others. Max ₹1,000/month.",
        "best_for": ["Online Shopping", "Grocery", "Food & Dining"],
        "color": "#003087",
    },

    "hdfc_cashback": {
        "display_name": "HDFC Cashback Card",
        "issuer": "HDFC",
        "annual_fee": 500,
        "fee_waiver_spend": 50000,
        "cashback": {
            "Online Shopping": 5.0,
            "Grocery":         5.0,
            "Food & Dining":   5.0,
            "Transport":       5.0,
            "Entertainment":   5.0,
            "Travel":          5.0,
            "Utilities & Bills": 5.0,
            "Health":          5.0,
            "Other":           1.0,
            "Fuel":            1.0,
            "Cash Advance":    0.0,
        },
        "offline_cashback": {
            "_default": 1.0,
            "Cash Advance": 0.0,
        },
        "monthly_cashback_cap": 3000,
        "notes": "5% on all online transactions; 1% offline. Max ₹3,000/month cashback. Fee waived at ₹50K annual spend.",
        "best_for": ["Online Shopping", "Food & Dining", "Utilities & Bills"],
        "color": "#003087",
    },

    "hdfc_swiggy": {
        "display_name": "HDFC Swiggy Credit Card",
        "issuer": "HDFC",
        "annual_fee": 500,
        "fee_waiver_spend": 200000,
        "cashback": {
            "Food & Dining":   10.0,
            "Grocery":         10.0,
            "Online Shopping": 5.0,
            "Entertainment":   5.0,
            "Transport":       5.0,
            "Travel":          5.0,
            "Utilities & Bills": 5.0,
            "Health":          5.0,
            "Other":           1.0,
            "Fuel":            1.0,
            "Cash Advance":    0.0,
        },
        "offline_cashback": {
            "_default": 1.0,
            "Cash Advance": 0.0,
        },
        "monthly_cashback_cap": 1500,
        "notes": "10% on Swiggy food & Instamart; 5% on all other online spend; 1% offline. Max ₹1,500/month.",
        "best_for": ["Food & Dining", "Grocery"],
        "color": "#FC8019",
    },

    "icici_amazon_pay": {
        "display_name": "ICICI Amazon Pay",
        "issuer": "ICICI",
        "annual_fee": 0,
        "fee_waiver_spend": 0,
        "cashback": {
            "Online Shopping": 5.0,
            "Grocery":         3.0,
            "Food & Dining":   2.0,
            "Transport":       2.0,
            "Entertainment":   2.0,
            "Travel":          2.0,
            "Utilities & Bills": 2.0,
            "Health":          2.0,
            "Other":           1.0,
            "Fuel":            1.0,
            "Cash Advance":    0.0,
        },
        "offline_cashback": {
            "_default": 1.0,
            "Other": 0.5,
            "Cash Advance": 0.0,
        },
        "monthly_cashback_cap": None,
        "notes": "5% on Amazon (Prime members); 2% on Amazon Pay partner merchants; 1% on all others. No annual fee.",
        "best_for": ["Online Shopping"],
        "color": "#FF9900",
    },

    "axis_ace": {
        "display_name": "Axis ACE Credit Card",
        "issuer": "Axis",
        "annual_fee": 0,
        "fee_waiver_spend": 0,
        "cashback": {
            "Utilities & Bills": 5.0,
            "Food & Dining":     4.0,
            "Transport":         4.0,
            "Online Shopping":   2.0,
            "Grocery":           2.0,
            "Entertainment":     2.0,
            "Travel":            2.0,
            "Health":            2.0,
            "Other":             2.0,
            "Fuel":              1.0,
            "Cash Advance":      0.0,
        },
        "offline_cashback": None,
        "monthly_cashback_cap": 500,
        "notes": "5% on bill payments/recharges via Google Pay; 4% on Swiggy, Zomato, Ola; 2% on all other spends. No annual fee. Max ₹500/month.",
        "best_for": ["Utilities & Bills", "Food & Dining", "Transport"],
        "color": "#97144D",
    },

    "axis_flipkart": {
        "display_name": "Axis Flipkart Credit Card",
        "issuer": "Axis",
        "annual_fee": 500,
        "fee_waiver_spend": 200000,
        "cashback": {
            "Online Shopping": 5.0,
            "Grocery":         4.0,
            "Food & Dining":   4.0,
            "Transport":       4.0,
            "Entertainment":   1.5,
            "Travel":          1.5,
            "Utilities & Bills": 1.5,
            "Health":          1.5,
            "Other":           1.5,
            "Fuel":            1.5,
            "Cash Advance":    0.0,
        },
        "offline_cashback": {
            "_default": 1.5,
            "Cash Advance": 0.0,
        },
        "monthly_cashback_cap": None,
        "notes": "5% on Flipkart/Myntra; 4% on grocery, Swiggy/Zomato; 1.5% on all others.",
        "best_for": ["Online Shopping", "Grocery", "Food & Dining"],
        "color": "#F74D05",
    },

    "sbi_cashback": {
        "display_name": "SBI Cashback Card",
        "issuer": "SBI",
        "annual_fee": 999,
        "fee_waiver_spend": 200000,
        "cashback": {
            "Online Shopping": 5.0,
            "Grocery":         5.0,
            "Food & Dining":   5.0,
            "Transport":       5.0,
            "Entertainment":   5.0,
            "Travel":          5.0,
            "Utilities & Bills": 5.0,
            "Health":          5.0,
            "Other":           1.0,
            "Fuel":            1.0,
            "Cash Advance":    0.0,
        },
        "offline_cashback": {
            "_default": 1.0,
            "Cash Advance": 0.0,
        },
        "monthly_cashback_cap": 5000,
        "notes": "5% cashback on all online transactions; 1% on offline. Max ₹5,000/month. Fee waived at ₹2L annual spend.",
        "best_for": ["Online Shopping", "Food & Dining", "Travel"],
        "color": "#1C4EA2",
    },

    "sbi_simply_click": {
        "display_name": "SBI SimplyCLICK",
        "issuer": "SBI",
        "annual_fee": 499,
        "fee_waiver_spend": 100000,
        "cashback": {
            "Online Shopping": 2.5,
            "Food & Dining":   2.5,
            "Transport":       2.5,
            "Travel":          2.5,
            "Grocery":         1.25,
            "Entertainment":   1.25,
            "Utilities & Bills": 0.25,
            "Health":          0.25,
            "Other":           0.25,
            "Fuel":            0.25,
            "Cash Advance":    0.0,
        },
        "offline_cashback": {
            "_default": 0.25,
            "Cash Advance": 0.0,
        },
        "monthly_cashback_cap": None,
        "notes": "10x RP on Amazon/Cleartrip/Zomato/Ola (≈2.5%); 5x on Swiggy/BookMyShow (≈1.25%); 1x on others (≈0.25%). Fee waived at ₹1L spend.",
        "best_for": ["Online Shopping", "Food & Dining", "Transport"],
        "color": "#1C4EA2",
    },

    "idfc_first_wealth": {
        "display_name": "IDFC FIRST Wealth",
        "issuer": "IDFC First",
        "annual_fee": 0,
        "fee_waiver_spend": 0,
        "cashback": {
            "Food & Dining":   3.0,
            "Entertainment":   3.0,
            "Online Shopping": 1.5,
            "Grocery":         1.5,
            "Transport":       1.5,
            "Travel":          1.5,
            "Utilities & Bills": 0.5,
            "Health":          0.5,
            "Other":           0.5,
            "Fuel":            0.5,
            "Cash Advance":    0.0,
        },
        "offline_cashback": {
            "Food & Dining":   3.0,
            "Entertainment":   3.0,
            "_default":        0.33,
            "Cash Advance":    0.0,
        },
        "monthly_cashback_cap": None,
        "notes": "10x RP on weekends at dining & entertainment (≈3%); 3x on all online (≈1.5%); 1x offline (≈0.5%). No annual fee.",
        "best_for": ["Food & Dining", "Entertainment", "Online Shopping"],
        "color": "#C8102E",
    },

    "amex_mrcc": {
        "display_name": "Amex Membership Rewards CC",
        "issuer": "Amex",
        "annual_fee": 1500,
        "fee_waiver_spend": 90000,
        "cashback": {
            "Online Shopping": 1.0,
            "Food & Dining":   1.0,
            "Grocery":         1.0,
            "Travel":          2.0,
            "Entertainment":   1.0,
            "Transport":       1.0,
            "Utilities & Bills": 1.0,
            "Health":          1.0,
            "Other":           1.0,
            "Fuel":            0.5,
            "Cash Advance":    0.0,
        },
        "offline_cashback": None,
        "monthly_cashback_cap": None,
        "notes": "1 MR point per ₹50 (≈1% value). Strong travel rewards and lounge access. Fee waived at ₹90K annual spend.",
        "best_for": ["Travel", "Online Shopping"],
        "color": "#016FD0",
    },
}
